swagger: '2.0'
info:
  title: API de Cervejas
  version: "0.1"
  description: Exemplo de uma API de cervejas
consumes:
  - application/json
produces:
  - application/json
paths:
  /ping:
    get:
      operationId: server.controllers.keep_alive_controller.ping
      summary: Verifica se o sistema está disponível
      responses:
        200:
          description: Retorna pong
  /cervejas:
    get:
      operationId: server.controllers.cervejas_controller.get_cervejas
      summary: Retorna todas as cervejas disponíveis da API
      parameters:
        - in: query
          name: teor_alcoolico_min
          description: Valor mínimo de teor alcóolico
          required: false
          type: number
          format: double
        - in: query
          name: teor_alcoolico_max
          description: Valor máximo de teor alcóolico
          required: false
          type: number
          format: double
      responses:
        200:
          description: Lista de cervejas
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Cerveja"
    post:
      operationId: server.controllers.cervejas_controller.post_cerveja
      summary: Cadastra uma nova cerveja
      parameters:
        - in: body
          name: cerveja_input
          description: Dados da nova cerveja
          required: true
          schema:
            $ref: "#/definitions/CervejaInput"
      responses:
        201:
          description: Nova cerveja cadastrada
          schema:
            $ref: "#/definitions/Cerveja"
  /cervejas/{id_cerveja}:
    get:
      operationId: server.controllers.cervejas_controller.get_cerveja
      summary: Retorna a cerveja correspondente ao id
      parameters:
        - in: path
          name: id_cerveja
          description: Identificador da cerveja
          required: true
          type: integer
          format: "int64"
      responses:
        200:
          description: Cerveja correspondente ao id
          schema:
            $ref: "#/definitions/Cerveja"
        404:
          description: Cerveja não encontrada
    delete:
      operationId: server.controllers.cervejas_controller.delete_cerveja
      summary: Remove a cerveja correspondente ao id
      parameters:
        - in: path
          name: id_cerveja
          description: Identificador da cerveja
          required: true
          type: integer
          format: "int64"
      responses:
        204:
          description: Cerveja removida
          schema:
            $ref: "#/definitions/Cerveja"
    put:
      operationId: server.controllers.cervejas_controller.put_cerveja
      summary: Atualiza a cerveja correspondente ao id
      parameters:
        - in: path
          name: id_cerveja
          description: Identificador da cerveja
          required: true
          type: integer
          format: "int64"
        - in: body
          name: cerveja_input
          description: Dados da nova cerveja
          required: true
          schema:
            $ref: "#/definitions/CervejaInput"
      responses:
        200:
          description: Cerveja atualizada
          schema:
            $ref: "#/definitions/Cerveja"
definitions:
  CervejaInput:
    type: object
    properties:
      nome:
        type: string
      estilo:
        type: string
      teor_alcoolico:
        type: number
        format: double
  Cerveja:
    type: object
    properties:
      id:
        type: integer
        format: int64
      nome:
        type: string
      estilo:
        type: string
      teor_alcoolico:
        type: number
        format: double